// <auto-generated />
using System;
using ColonyTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ColonyTracker.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611161552_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("ColonyTracker.Api.Models.ColonyState", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Act")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColonyStress")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DarkwingChange")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DarkwingDesires")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DarkwingKnowledge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DarkwingMaintains")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DarkwingRitual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DarkwingSacrifices")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DominantFactions")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfluenceNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("MajorConsequences")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionSummary")
                        .HasColumnType("TEXT");

                    b.Property<int>("Week")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ColonyStates");
                });

            modelBuilder.Entity("ColonyTracker.Api.Models.Faction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AfraidOf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CertainOf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Change")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoreTenet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Desires")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Knowledge")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Maintains")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryTension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Represents")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RightAbout")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Ritual")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Sacrifices")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SingleSentence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WrongAbout")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Factions");
                });

            modelBuilder.Entity("ColonyTracker.Api.Models.RelationshipOverride", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScoreBump")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RelationshipOverrides");
                });

            modelBuilder.Entity("ColonyTracker.Api.Models.RulesConfig", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("AgencyChange")
                        .HasColumnType("REAL");

                    b.Property<double>("AgencyKnowledge")
                        .HasColumnType("REAL");

                    b.Property<double>("AgencyRitual")
                        .HasColumnType("REAL");

                    b.Property<double>("ChangeConflict")
                        .HasColumnType("REAL");

                    b.Property<double>("ChangeMatch")
                        .HasColumnType("REAL");

                    b.Property<double>("DesireVsSacrifice")
                        .HasColumnType("REAL");

                    b.Property<double>("KnowledgeConflict")
                        .HasColumnType("REAL");

                    b.Property<double>("KnowledgeMatch")
                        .HasColumnType("REAL");

                    b.Property<double>("MaintainsVsSacrifice")
                        .HasColumnType("REAL");

                    b.Property<double>("RitualConflict")
                        .HasColumnType("REAL");

                    b.Property<double>("RitualMatch")
                        .HasColumnType("REAL");

                    b.Property<double>("SharedDesire")
                        .HasColumnType("REAL");

                    b.Property<double>("SharedMaintains")
                        .HasColumnType("REAL");

                    b.Property<double>("StabilityChange")
                        .HasColumnType("REAL");

                    b.Property<double>("StabilityKnowledge")
                        .HasColumnType("REAL");

                    b.Property<double>("StabilityRitual")
                        .HasColumnType("REAL");

                    b.Property<double>("StressNegativeMultiplierPerPoint")
                        .HasColumnType("REAL");

                    b.Property<double>("StressPositiveMultiplierPerPoint")
                        .HasColumnType("REAL");

                    b.Property<string>("ThresholdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TruthChange")
                        .HasColumnType("REAL");

                    b.Property<double>("TruthKnowledge")
                        .HasColumnType("REAL");

                    b.Property<double>("TruthRitual")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("RulesConfigs");
                });

            modelBuilder.Entity("ColonyTracker.Api.Models.SessionLogEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Act")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColonyStressChange")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DarkwingActions")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("FactionChanges")
                        .HasColumnType("TEXT");

                    b.Property<string>("FutureConsequences")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationshipBumps")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<int>("Week")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SessionLog");
                });
#pragma warning restore 612, 618
        }
    }
}
