// <auto-generated />
using System;
using ColonyTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ColonyTracker.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616203122_AddSessionsAndEvents")]
    partial class AddSessionsAndEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("ColonyTracker.Api.Models.Character", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AgencyValue")
                        .HasColumnType("REAL");

                    b.Property<string>("Ancestry")
                        .HasColumnType("TEXT");

                    b.Property<string>("Background")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Change")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .HasColumnType("TEXT");

                    b.Property<int>("Conviction")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DoubtDirection")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FactionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fears")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("Goals")
                        .HasColumnType("TEXT");

                    b.Property<string>("Heritage")
                        .HasColumnType("TEXT");

                    b.Property<int>("Impressionable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Influence")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Knowledge")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Occupation")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pressure")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Ritual")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SocialClassId")
                        .HasColumnType("TEXT");

                    b.Property<double>("StabilityValue")
                        .HasColumnType("REAL");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<double>("TruthValue")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("ColonyTracker.Api.Models.ColonyState", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Act")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColonyStress")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DominantFactions")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfluenceNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("MajorConsequences")
                        .HasColumnType("TEXT");

                    b.Property<double>("PartyAgencyValue")
                        .HasColumnType("REAL");

                    b.Property<int>("PartyChange")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartyKnowledge")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PartyRitual")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PartyStabilityValue")
                        .HasColumnType("REAL");

                    b.Property<double>("PartyTruthValue")
                        .HasColumnType("REAL");

                    b.Property<string>("SessionSummary")
                        .HasColumnType("TEXT");

                    b.Property<int>("Week")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ColonyStates");
                });

            modelBuilder.Entity("ColonyTracker.Api.Models.Event", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("ColonyTracker.Api.Models.EventEffect", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("Delta")
                        .HasColumnType("REAL");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Property")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("EventEffects");
                });

            modelBuilder.Entity("ColonyTracker.Api.Models.Faction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AfraidOf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("AgencyValue")
                        .HasColumnType("REAL");

                    b.Property<int>("BaseInfluence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CertainOf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Change")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoreTenet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Knowledge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Legitimacy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Momentum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Represents")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RightAbout")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Ritual")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SingleSentence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<double>("StabilityValue")
                        .HasColumnType("REAL");

                    b.Property<double>("TruthValue")
                        .HasColumnType("REAL");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WrongAbout")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Factions");
                });

            modelBuilder.Entity("ColonyTracker.Api.Models.RelationshipOverride", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScoreBump")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RelationshipOverrides");
                });

            modelBuilder.Entity("ColonyTracker.Api.Models.RulesConfig", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("BeliefConflict")
                        .HasColumnType("REAL");

                    b.Property<double>("BeliefMatch")
                        .HasColumnType("REAL");

                    b.Property<double>("InfluenceConvictionScale")
                        .HasColumnType("REAL");

                    b.Property<bool>("NegativeEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PositiveEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<double>("StressNegativeMultiplierPerPoint")
                        .HasColumnType("REAL");

                    b.Property<double>("StressPositiveMultiplierPerPoint")
                        .HasColumnType("REAL");

                    b.Property<string>("ThresholdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ValueAlignmentScale")
                        .HasColumnType("REAL");

                    b.Property<double>("ValueConflictScale")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("RulesConfigs");
                });

            modelBuilder.Entity("ColonyTracker.Api.Models.Session", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Act")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Week")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("ColonyTracker.Api.Models.SessionLogEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Act")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColonyStressChange")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("FactionChanges")
                        .HasColumnType("TEXT");

                    b.Property<string>("FutureConsequences")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartyActions")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationshipBumps")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<int>("Week")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SessionLog");
                });

            modelBuilder.Entity("ColonyTracker.Api.Models.Event", b =>
                {
                    b.HasOne("ColonyTracker.Api.Models.Session", "Session")
                        .WithMany("Events")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ColonyTracker.Api.Models.EventEffect", b =>
                {
                    b.HasOne("ColonyTracker.Api.Models.Event", "Event")
                        .WithMany("Effects")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("ColonyTracker.Api.Models.Event", b =>
                {
                    b.Navigation("Effects");
                });

            modelBuilder.Entity("ColonyTracker.Api.Models.Session", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
